# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NYTimesPlayground' do
  use_frameworks!
  pod 'Nuke', '~> 4.0' # images: loading/caching/batched requests, etc.

end

